### ISSUE TITLE
yy >= 17 ? seriously?

### ISSUE THREAD

**Issue by stereodenis** [cloudipsp/react-native-cloudipsp#2]
```
__isValidExpireYearValue__ = (yy) => {
    return yy >= 17 && yy <= 99;
  }
```
https://github.com/cloudipsp/react-native-cloudipsp/blob/master/cloudipsp.js#L180

**Comment by berehovyi** [comment]
Please, explain what problem you seeing in ?

**Comment by stereodenis** [comment]
@vberegovoy 
In the next 2018, the 2017 cards will be valid and you will have to change the code

**Comment by berehovyi** [comment]
In 2018 local validation will not works for old SDKs, but server will validate this card number and you'll receive error about in response.

**Comment by stereodenis** [comment]
@vberegovoy 
Почему сразу нельзя написать нормальный код проверки?
это всего лишь проверка по введённым месяцу и году на актуальность даты.

пс: я молчу уже про то, что вы просто с форсом спушили новую версию и понять, что изменилось практически(спасибо форкам) невозможно
