### ISSUE TITLE
Invalid card number 1015

### ISSUE THREAD

**Issue by ayazzali** [cloudipsp/react-native-cloudipsp#9]
I've cloned your repo
then npm i npm start
typed card data 
and i got 1015 decline. but i've typed card number correctly.
![image](https://user-images.githubusercontent.com/19633435/72425720-60190d80-3799-11ea-94c0-dc3a32f9421f.png)

used real phone. debug through adb)

**Comment by fondyeu** [comment]
please use test cards with test merchant id 1396424: https://docs.fondy.eu/docs/page/2/

**Comment by ayazzali** [comment]
thanks, ive tried and it works.
but how can i try with real card?

and how can i use it with RN 0.60 - they removed webview from RN.

**Comment by fondyeu** [comment]
you need to register merchant in Merchant Portal https://portal.fondy.eu/mportal/ with the functioning site/business and pass the onboarding procedures. Only after approval, you can accept real cards.
